sudo: required
services:
  - docker

before_install:
  - docker build -t colingranada/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true colingranada/react-test npm test

after_success:
  - docker build -t colingranada/multi-client ./client
  - docker build -t colingranada/multi-nginx ./nginx
  - docker build -t colingranada/multi-server ./server
  - docker build -t colingranada/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push colingranada/multi-client
  - docker push colingranada/multi-nginx
  - docker push colingranada/multi-server
  - docker push colingranada/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-791600241684"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


